apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-sync.fullname" . }}
  labels:
    {{- include "cert-manager-sync.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cert-manager-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := dict }}
      {{- if and .Values.metrics .Values.metrics.enabled }}
      {{- $_ := set $annotations "prometheus.io/scrape" "true" }}
      {{- $_ := set $annotations "prometheus.io/port" (.Values.metrics.port | toString) }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      {{- $annotations = merge $annotations .Values.podAnnotations }}
      {{- end }}
      {{- if $annotations }}
      annotations:
        {{- toYaml $annotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cert-manager-sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cert-manager-sync.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: OPERATOR_NAME
            value: "{{ .Values.config.operatorName }}"
          - name: SECRETS_NAMESPACE
            value: "{{ .Values.config.secretsNamespace }}"
          - name: DISABLED_NAMESPACES
            value: "{{ .Values.config.disabledNamespaces }}"
          - name: ENABLED_NAMESPACES
            value: "{{ .Values.config.enabledNamespaces }}"
          - name: LOG_LEVEL
            value: "{{ .Values.config.logLevel }}"
          - name: LOG_FORMAT
            value: "{{ .Values.config.logFormat }}"
          - name: CACHE_DISABLE
            value: "{{ .Values.config.disableCache }}"
          - name: ENABLE_METRICS
            value: "{{ if and .Values.metrics .Values.metrics.enabled }}{{ .Values.metrics.enabled }}{{ else }}false{{ end }}"
          - name: METRICS_PORT
            value: "{{ if and .Values.metrics .Values.metrics.port }}{{ .Values.metrics.port }}{{ else }}9090{{ end }}"
          {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if and .Values.metrics .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
